// <auto-generated />
using System;
using AttendanceManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AttendanceManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260929181504_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AttendanceManagement.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("AttendanceManagement.Models.Equipement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeExterne")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Equipements");
                });

            modelBuilder.Entity("AttendanceManagement.Models.HistoriqueAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatePointage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeId")
                        .HasColumnType("integer");

                    b.Property<string>("TypeAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HistoriqueActions");
                });

            modelBuilder.Entity("AttendanceManagement.Models.Pointage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePointage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("integer");

                    b.Property<string>("Equipement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Evenement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("HeureModifiee")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HeurePointage")
                        .HasColumnType("interval");

                    b.Property<string>("IdEquipement")
                        .HasColumnType("text");

                    b.Property<string>("Porte")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.ToTable("Pointages");
                });

            modelBuilder.Entity("AttendanceManagement.Models.Pointage", b =>
                {
                    b.HasOne("AttendanceManagement.Models.Employe", "Employe")
                        .WithMany("Pointages")
                        .HasForeignKey("EmployeId");

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("AttendanceManagement.Models.Employe", b =>
                {
                    b.Navigation("Pointages");
                });
#pragma warning restore 612, 618
        }
    }
}
